In [1]:
import sys
sys.path.insert(0, 'C:/Users/vinicius_martins/Documents/GitHub/flappybird/')

In [2]:
import AI as ai

In [3]:
input_shape = 3

In [4]:
population = ai.create_new_population(10, input_shape)
population

[[0,
  0,
  [array([[1.1502951 ],
          [0.53152   ],
          [0.30904698]], dtype=float32),
   array([0.40262184], dtype=float32)],
  0],
 [1,
  0,
  [array([[-1.1765476 ],
          [ 1.0864807 ],
          [-0.32036233]], dtype=float32),
   array([0.616553], dtype=float32)],
  0],
 [2,
  0,
  [array([[-1.1039329 ],
          [ 0.12460864],
          [ 0.73841774]], dtype=float32),
   array([-0.5532664], dtype=float32)],
  0],
 [3,
  0,
  [array([[ 0.2542578],
          [ 0.5589136],
          [-0.9842095]], dtype=float32),
   array([-0.8796099], dtype=float32)],
  0],
 [4,
  0,
  [array([[-0.8446822 ],
          [-0.51837116],
          [-0.26079834]], dtype=float32),
   array([-2.041927], dtype=float32)],
  0],
 [5,
  0,
  [array([[ 0.93788135],
          [ 0.08060098],
          [-1.0484025 ]], dtype=float32),
   array([-1.6298534], dtype=float32)],
  0],
 [6,
  0,
  [array([[-0.0193665 ],
          [-1.0984278 ],
          [-0.28126943]], dtype=float32),
   array([0.8585815

In [5]:
fitness = 10
population[0][1] += fitness

In [6]:
population[0]

[0,
 10,
 [array([[1.1502951 ],
         [0.53152   ],
         [0.30904698]], dtype=float32),
  array([0.40262184], dtype=float32)],
 0]

In [7]:
fitness = 10
population[5][1] += fitness
population[5]

[5,
 10,
 [array([[ 0.93788135],
         [ 0.08060098],
         [-1.0484025 ]], dtype=float32),
  array([-1.6298534], dtype=float32)],
 0]

In [8]:
new_population = ai.new_generation(population, input_shape)

Mantendo: 2 melhores individuos 
Criando: 2 sobreviventes 
Criando: 6 novos individuos


In [9]:
population

[[0,
  0,
  [array([[1.1502951 ],
          [0.53152   ],
          [0.30904698]], dtype=float32),
   array([0.40262184], dtype=float32)],
  1],
 [1,
  0,
  [array([[-1.1765476 ],
          [ 1.0864807 ],
          [-0.32036233]], dtype=float32),
   array([0.616553], dtype=float32)],
  0],
 [2,
  0,
  [array([[-1.1039329 ],
          [ 0.12460864],
          [ 0.73841774]], dtype=float32),
   array([-0.5532664], dtype=float32)],
  0],
 [3,
  0,
  [array([[ 0.2542578],
          [ 0.5589136],
          [-0.9842095]], dtype=float32),
   array([-0.8796099], dtype=float32)],
  0],
 [4,
  0,
  [array([[-0.8446822 ],
          [-0.51837116],
          [-0.26079834]], dtype=float32),
   array([-2.041927], dtype=float32)],
  0],
 [1,
  0,
  [array([[ 0.93788135],
          [ 0.08060098],
          [-1.0484025 ]], dtype=float32),
   array([-1.6298534], dtype=float32)],
  1],
 [6,
  0,
  [array([[-0.0193665 ],
          [-1.0984278 ],
          [-0.28126943]], dtype=float32),
   array([0.8585815

In [10]:
new_population[:2]

[[0,
  0,
  [array([[1.1502951 ],
          [0.53152   ],
          [0.30904698]], dtype=float32),
   array([0.40262184], dtype=float32)],
  1],
 [1,
  0,
  [array([[ 0.93788135],
          [ 0.08060098],
          [-1.0484025 ]], dtype=float32),
   array([-1.6298534], dtype=float32)],
  1]]

In [214]:
from AI._algoritimo_genetico import make_parents, make_survivors, make_new_individuos, reset_scores

In [12]:
population = ai.create_new_population(10, input_shape)
population

[[0,
  0,
  [array([[-0.02566028],
          [ 0.6344907 ],
          [ 0.42750633]], dtype=float32),
   array([-0.7100167], dtype=float32)],
  0],
 [1,
  0,
  [array([[ 0.3095641 ],
          [-0.95928097],
          [-1.035088  ]], dtype=float32),
   array([0.7323673], dtype=float32)],
  0],
 [2,
  0,
  [array([[-0.7581034 ],
          [ 0.00976717],
          [-0.929392  ]], dtype=float32),
   array([-1.5241913], dtype=float32)],
  0],
 [3,
  0,
  [array([[-0.5765015 ],
          [-0.68019485],
          [-0.65754896]], dtype=float32),
   array([0.24223046], dtype=float32)],
  0],
 [4,
  0,
  [array([[-0.18683982],
          [ 1.0837971 ],
          [-0.85778344]], dtype=float32),
   array([-0.46536013], dtype=float32)],
  0],
 [5,
  0,
  [array([[-0.5452914],
          [ 0.7649338],
          [-0.9062017]], dtype=float32),
   array([0.32237163], dtype=float32)],
  0],
 [6,
  0,
  [array([[ 0.6753546 ],
          [-0.8601773 ],
          [ 0.44312143]], dtype=float32),
   array([0.8

In [13]:
fitness = 10
population[3][1] += fitness
population[6][1] += fitness

In [14]:
population[6]

[6,
 10,
 [array([[ 0.6753546 ],
         [-0.8601773 ],
         [ 0.44312143]], dtype=float32),
  array([0.81248474], dtype=float32)],
 0]

In [15]:
population_sorted = sorted(population, key=lambda column: column[1], reverse=True)
population_sorted[:2]

[[3,
  10,
  [array([[-0.5765015 ],
          [-0.68019485],
          [-0.65754896]], dtype=float32),
   array([0.24223046], dtype=float32)],
  0],
 [6,
  10,
  [array([[ 0.6753546 ],
          [-0.8601773 ],
          [ 0.44312143]], dtype=float32),
   array([0.81248474], dtype=float32)],
  0]]

In [210]:
elitism = 2
parents = make_parents(population_sorted, elitism)
parents

[[3,
  10,
  [array([[-0.5765015 ],
          [-0.68019485],
          [-0.65754896]], dtype=float32),
   array([0.24223046], dtype=float32)],
  0],
 [6,
  10,
  [array([[ 0.6753546 ],
          [-0.8601773 ],
          [ 0.44312143]], dtype=float32),
   array([0.81248474], dtype=float32)],
  0]]

In [212]:
survivors = make_survivors(population_sorted, elitism, 0.2, 0.5, 0.1)
survivors

[[3,
  10,
  [array([[-0.57650149],
          [-0.68019485],
          [ 0.44312143]]),
   array([0.81248474])],
  0],
 [6,
  10,
  [array([[-0.57650149],
          [-0.86017728],
          [ 0.44312143]]),
   array([0.81248474])],
  0]]

In [53]:
import numpy as np

In [208]:
n_sobreviventes = 10
print(0)
if n_sobreviventes > 1:
    print(np.random.randint(1, n_sobreviventes))

0
2


In [18]:
n_population = len(population)
n_parents = len(parents)
n_survivors = len(survivors)
print(n_population)
print(n_parents)
print(n_survivors)

10
2
2


In [19]:
10-2-2

6

In [209]:
new_individuos = make_new_individuos(input_shape, n_population, n_parents, n_survivors)
new_individuos

[[0,
  0,
  [array([[-1.1003186 ],
          [-0.610315  ],
          [ 0.86221135]], dtype=float32),
   array([-0.3420352], dtype=float32)],
  0],
 [1,
  0,
  [array([[ 0.93575585],
          [ 0.93086493],
          [-1.0081469 ]], dtype=float32),
   array([-1.3114585], dtype=float32)],
  0],
 [2,
  0,
  [array([[ 0.9301261 ],
          [-1.0781672 ],
          [-0.13097894]], dtype=float32),
   array([-1.8824751], dtype=float32)],
  0],
 [3,
  0,
  [array([[-0.4386024 ],
          [-0.748278  ],
          [-0.24542445]], dtype=float32),
   array([0.71508086], dtype=float32)],
  0],
 [4,
  0,
  [array([[-0.03973567],
          [ 0.05013931],
          [-0.5440227 ]], dtype=float32),
   array([-0.18692723], dtype=float32)],
  0],
 [5,
  0,
  [array([[ 0.5638161 ],
          [-0.3636899 ],
          [ 0.30333304]], dtype=float32),
   array([-0.33624384], dtype=float32)],
  0]]

In [213]:
new_generation = parents + survivors + new_individuos
new_generation

[[3,
  10,
  [array([[-0.5765015 ],
          [-0.68019485],
          [-0.65754896]], dtype=float32),
   array([0.24223046], dtype=float32)],
  0],
 [6,
  10,
  [array([[ 0.6753546 ],
          [-0.8601773 ],
          [ 0.44312143]], dtype=float32),
   array([0.81248474], dtype=float32)],
  0],
 [3,
  10,
  [array([[-0.57650149],
          [-0.68019485],
          [ 0.44312143]]),
   array([0.81248474])],
  0],
 [6,
  10,
  [array([[-0.57650149],
          [-0.86017728],
          [ 0.44312143]]),
   array([0.81248474])],
  0],
 [0,
  0,
  [array([[-1.1003186 ],
          [-0.610315  ],
          [ 0.86221135]], dtype=float32),
   array([-0.3420352], dtype=float32)],
  0],
 [1,
  0,
  [array([[ 0.93575585],
          [ 0.93086493],
          [-1.0081469 ]], dtype=float32),
   array([-1.3114585], dtype=float32)],
  0],
 [2,
  0,
  [array([[ 0.9301261 ],
          [-1.0781672 ],
          [-0.13097894]], dtype=float32),
   array([-1.8824751], dtype=float32)],
  0],
 [3,
  0,
  [array([

In [215]:
reset_scores(new_generation)

[[0,
  0,
  [array([[-0.5765015 ],
          [-0.68019485],
          [-0.65754896]], dtype=float32),
   array([0.24223046], dtype=float32)],
  1],
 [1,
  0,
  [array([[ 0.6753546 ],
          [-0.8601773 ],
          [ 0.44312143]], dtype=float32),
   array([0.81248474], dtype=float32)],
  1],
 [2,
  0,
  [array([[-0.57650149],
          [-0.68019485],
          [ 0.44312143]]),
   array([0.81248474])],
  1],
 [3,
  0,
  [array([[-0.57650149],
          [-0.86017728],
          [ 0.44312143]]),
   array([0.81248474])],
  1],
 [4,
  0,
  [array([[-1.1003186 ],
          [-0.610315  ],
          [ 0.86221135]], dtype=float32),
   array([-0.3420352], dtype=float32)],
  1],
 [5,
  0,
  [array([[ 0.93575585],
          [ 0.93086493],
          [-1.0081469 ]], dtype=float32),
   array([-1.3114585], dtype=float32)],
  1],
 [6,
  0,
  [array([[ 0.9301261 ],
          [-1.0781672 ],
          [-0.13097894]], dtype=float32),
   array([-1.8824751], dtype=float32)],
  1],
 [7,
  0,
  [array([[-0.

In [22]:
from copy import deepcopy

In [23]:
population[:2]

[[0,
  0,
  [array([[-0.02566028],
          [ 0.6344907 ],
          [ 0.42750633]], dtype=float32),
   array([-0.7100167], dtype=float32)],
  0],
 [1,
  0,
  [array([[ 0.3095641 ],
          [-0.95928097],
          [-1.035088  ]], dtype=float32),
   array([0.7323673], dtype=float32)],
  0]]

In [24]:
teste = deepcopy(population[:2])
teste[0][1] += 10

In [25]:
teste

[[0,
  10,
  [array([[-0.02566028],
          [ 0.6344907 ],
          [ 0.42750633]], dtype=float32),
   array([-0.7100167], dtype=float32)],
  0],
 [1,
  0,
  [array([[ 0.3095641 ],
          [-0.95928097],
          [-1.035088  ]], dtype=float32),
   array([0.7323673], dtype=float32)],
  0]]